---
#--- Indices --------------------------------

- symbol          : ES
  name            : E-Mini S&P 500
  increment       : 0.25
  market          : IN
  product         : FU
  exchange        : CME
  pointValue      : 50
  costPerOperation: 30
  margin          : 0
  strategies      : reversal(good), trendf(hard), bias(no)

- symbol          : MES
  name            : Micro E-Mini S&P 500
  increment       : 0.25
  market          : IN
  product         : FU
  exchange        : CME
  pointValue      : 5
  costPerOperation: 4
  margin          : 1314
  strategies      : reversal(good), trendf(hard), bias(no)

- symbol          : NQ
  name            : E-Mini Nasdaq-100
  increment       : 0.25
  market          : IN
  product         : FU
  exchange        : CME
  pointValue      : 20
  costPerOperation: 40
  margin          : 36070

- symbol          : MNQ
  name            : Micro E-mini Nasdaq 100
  increment       : 0.25
  market          : IN
  product         : FU
  exchange        : CME
  pointValue      : 2
  costPerOperation: 5
  margin          : 3607

- symbol          : YM
  name            : Mini Dow Jones 30
  increment       : 1
  market          : IN
  product         : FU
  exchange        : CME
  pointValue      : 5
  costPerOperation: 0
  margin          : 12800

- symbol          : MYM
  name            : Micro Dow Jones 30
  increment       : 1
  market          : IN
  product         : FU
  exchange        : CME
  pointValue      : 0.5
  costPerOperation: 5
  margin          : 1280

- symbol          : FDAX
  name            : DAX
  increment       : 1
  market          : IN
  product         : FU
  exchange        : EUREX
  pointValue      : 25
  costPerOperation: 0
  margin          : 0
  strategies      : bias(good), reversal(good,first-half-day), trendf(intraday)

- symbol          : FDXM
  name            : Mini DAX
  increment       : 1
  market          : IN
  product         : FU
  exchange        : EUREX
  pointValue      : 5
  costPerOperation: 0
  margin          : 0
  strategies      : bias, reversal(first-half-day), intraday

- symbol          : FDXS
  name            : Micro DAX
  increment       : 1
  market          : IN
  product         : FU
  exchange        : EUREX
  pointValue      : 1
  costPerOperation: 6
  margin          : 1600
  strategies      : bias, reversal(first-half-day), intraday

#--- Metals --------------------------------

- symbol          : GC
  name            : Gold
  increment       : 0.1
  market          : ME
  product         : FU
  exchange        : COMEX
  pointValue      : 100
  costPerOperation: 20
  margin          : 16034
  strategies      : bias

- symbol          : MGC
  name            : Micro Gold
  increment       : 0.1
  market          : ME
  product         : FU
  exchange        : COMEX
  pointValue      : 10
  costPerOperation: 4
  margin          : 1604
  strategies      : bias

- symbol          : PL
  name            : Platinum
  increment       : 0.1
  market          : ME
  product         : FU
  exchange        : NYMEX
  pointValue      : 50
  costPerOperation: 0
  margin          : 0

- symbol          : SI
  name            : Silver
  increment       : 0.005
  market          : ME
  product         : FU
  exchange        : COMEX
  pointValue      : 5000
  costPerOperation: 0
  margin          : 0

- symbol          : HG
  name            : Copper
  increment       : 0.0005
  market          : ME
  product         : FU
  exchange        : COMEX
  pointValue      : 25000
  costPerOperation: 0
  margin          : 0

- symbol          : MHG
  name            : Copper
  increment       : 0.0005
  market          : ME
  product         : FU
  exchange        : COMEX
  pointValue      : 2500
  costPerOperation: 0
  margin          : 0

#--- Energy --------------------------------

- symbol          : CL
  name            : Crude Oil
  increment       : 0.01
  market          : EN
  product         : FU
  exchange        : NYMEX
  pointValue      : 1000
  costPerOperation: 30
  margin          : 0
  strategies      : bias(good), reversal(no), trendf(intraday, overnight), 5min

- symbol          : MCL
  name            : Micro Crude Oil
  increment       : 0.01
  market          : EN
  product         : FU
  exchange        : NYMEX
  pointValue      : 100
  costPerOperation: 4
  margin          : 2700
  strategies      : bias(good), reversal(no), trendf(intraday, overnight), 5min

- symbol          : HO
  name            : Heating Oil
  increment       : 0.0001
  market          : EN
  product         : FU
  exchange        : NYMEX
  pointValue      : 42000
  costPerOperation: 0
  margin          : 0

- symbol          : NG
  name            : Natural Gas
  increment       : 0.001
  market          : EN
  product         : FU
  exchange        : NYMEX
  pointValue      : 10000
  costPerOperation: 0
  margin          : 0

- symbol          : RB
  name            : RBOB Gasoline
  increment       : 0.0001
  market          : EN
  product         : FU
  exchange        : NYMEX
  pointValue      : 42000
  costPerOperation: 0
  margin          : 0

#--- Currencies --------------------------------

- symbol          : 6A
  name            : Australian Dollar
  increment       : 0.00005
  market          : FX
  product         : FU
  exchange        : CME
  pointValue      : 100000
  costPerOperation: 0
  margin          : 0

- symbol          : 6B
  name            : British Pound
  increment       : 0.0001
  market          : FX
  product         : FU
  exchange        : CME
  pointValue      : 62500
  costPerOperation: 0
  margin          : 2977

- symbol          : M6B
  name            : Micro British Pound
  increment       : 0.0001
  market          : FX
  product         : FU
  exchange        : CME
  pointValue      : 6250
  costPerOperation: 2
  margin          : 313

- symbol          : 6C
  name            : Canadian Dollar
  increment       : 0.00005
  market          : FX
  product         : FU
  exchange        : CME
  pointValue      : 100000
  costPerOperation: 0
  margin          : 0

- symbol          : 6E
  name            : Euro FX
  increment       : 0.00005
  market          : FX
  product         : FU
  exchange        : CME
  pointValue      : 125000
  costPerOperation: 8
  margin          : 3685
  strategies      : bias, 5min

- symbol          : E7
  name            : E-Mini Euro FX
  increment       : 0.0001
  market          : FX
  product         : FU
  exchange        : CME
  pointValue      : 62500
  costPerOperation: 8
  margin          : 1842
  strategies      : bias, reversal 1h, 5min

- symbol          : 6J
  name            : Japanese Yen
  increment       : 0.0000001
  market          : FX
  product         : FU
  exchange        : CME
  pointValue      : 12500000
  costPerOperation: 0
  margin          : 0

#--- Grains --------------------------------

- symbol          : ZS
  name            : Soybeans
  increment       :
  market          : GR
  product         : FU
  exchange        : CBOT
  pointValue      :
  costPerOperation: 50
  margin          : 0

- symbol          : ZC
  name            : Corn
  increment       :
  market          : GR
  product         : FU
  exchange        : CBOT
  pointValue      :
  costPerOperation: 0
  margin          : 0

- symbol          : ZW
  name            : Wheat Futures
  increment       : 0.0025
  market          : GR
  product         : FU
  exchange        : CBOT
  pointValue      : 5000
  costPerOperation: 0
  margin          : 2800
  notes           : Verify pointValue & increment

#--- Softs --------------------------------

- symbol          : KC
  name            : Coffee "C"
  increment       : 0.05
  market          : SO
  product         : FU
  exchange        : IFUS
  pointValue      : 375
  costPerOperation: 0
  margin          : 0

- symbol          : CT
  name            : Cotton N. 2
  increment       : 0.01
  market          : SO
  product         : FU
  exchange        : IFUS
  pointValue      : 500
  costPerOperation: 0
  margin          : 0

#--- Bonds --------------------------------

- symbol          : ZN
  name            : 10 Yr U.S. Treasury Notes
  increment       : 0.015625
  market          : BO
  product         : FU
  exchange        : CBOT
  pointValue      : 1000
  costPerOperation: 0
  margin          : 0

- symbol          : ZB
  name            : U.S. Treasury Bond
  increment       : 0.03125
  market          : BO
  product         : FU
  exchange        : CBOT
  pointValue      : 1000
  costPerOperation: 0
  margin          : 0

#--- Meats --------------------------------

- symbol          : GF
  name            : Feeder Cattle
  increment       :
  market          : MT
  product         : FU
  exchange        : CME
  pointValue      :
  costPerOperation: 0
  margin          : 0

- symbol          : HE
  name            : Lean Hog
  increment       :
  market          : MT
  product         : FU
  exchange        : CME
  pointValue      :
  costPerOperation: 0
  margin          : 0
  strategies      : overnight

- symbol          : LE
  name            : Live Cattle
  increment       :
  market          : MT
  product         : FU
  exchange        : CME
  pointValue      :
  costPerOperation: 0
  margin          : 0
  strategies      : reversal(good), trendf(overnight, weak), bias(no)

# cocoa: overnight
