# ==============================================================================
# ===
# === Buttons
# ===
# ==============================================================================

button:
  create:   CREATE
  view:     VIEW
  edit:     EDIT
  filter:   FILTER
  save:     SAVE
  run:      RUN
  optimize: OPTIMIZE
  reload:   RELOAD
  cancel:   CANCEL

# ==============================================================================
# ===
# === Left menu
# ===
# ==============================================================================

menu:
  main:
    _label: Main
    home: Home
  inventory:
    _label: Inventory
    tradingSystem: Trading systems
  portfolio:
    _label: Portfolio
    tradingSystem: Trading systems
    monitoring   : Monitoring
  admin:
    _label: Administration
    connections  : Connections
    config       : Configuration
    link         : GitHub

# ==============================================================================
# ===
# === Flex table
# ===
# ==============================================================================

flexTable:
  noData: No data

# ==============================================================================
# ===
# === Model
# ===
# ==============================================================================

model:
  tradingSystem:
    id              : Id
    createdAt       : Created at
    updatedAt       : Updated at
    name            : Name
    portfolioName   : Portfolio
    feedSymbol      : Feed symbol
    brokerSymbol    : Broker symbol
    tradingSession  : Session

    code            : Code
    firstUpdate     : First update
    lastUpdate      : Last update
    closedProfit    : Closed profit
    tradingDays     : Trading days
    numTrades       : Num. of trades
    filterType      : Filter type
    filter          : Filter
    status          : Status

  instrument:
    id             : Id
    ticker         : Ticker;
    name           : Name;
    createdAt      : Created at
    updatedAt      : Updated at

  connection:
    id                   : Id
    username             : Username
    code                 : Code
    name                 : Name
    systemCode           : System code
    systemName           : System name
    connectionCode       : Connected
    supportsFeed         : Feed
    supportsBroker       : Broker
    supportsMultipleFeeds: MFeeds
    supportsInventory    : Inventory
    createdAt            : Created at
    updatedAt            : Updated at

# ==============================================================================
# ===
# === Pages
# ===
# ==============================================================================

page:
  header:
    title: BitFever platform
  unknown:
    message: Unknown page
  # ==============================================================================

  inventory:
    tradingSystem:
      new:           New trading system
      name:          Name
      workspaceCode: Workspace
      portfolio:     Portfolio
      feed:          Feed symbol
      broker:        Broker symbol
      session:       Trading session

  # ==============================================================================

  admin:
    config:
      title: Configuration

    # ----------------------------------------------------------------------------

    connection:
      new: New connection
      code: Code
      name: Name
      system: System

  # ==============================================================================

  portfolio:
    tradingSystem:
      status:
        en: Enabled
        di: Disabled

    # ----------------------------------------------------------------------------

    monitoring:
      portfolios: Portfolios
      tradingSystems: Trading systems
      options: Options
      period: Period
      periods:
        - id: 30
          name: Last month
        - id: 60
          name: Last 2 months
        - id: 90
          name: Last 3 months
        - id: 180
          name: Last 6 months
        - id: 365
          name: Last year
        - id: 730
          name: Last 2 years
      chartType: Chart type
      chartTypes:
        - id: equities
          name: Equities
        - id: trades
          name: Trades
      showTotals:   Totals
      showRawProfit:   Raw profits
      showNetProfit:   Net profits
      showRawDrawdown: Raw drawdowns
      showNetDrawdown: Net drawdowns

      totalRawProfit:   Total raw profit
      totalNetProfit:   Total net profit
      totalRawDrawdown: Total raw drawdown
      totalNetDrawdown: Total net drawdown
      totalTrades:      Total trades

    # ----------------------------------------------------------------------------

    filtering:
      weeks: Weeks
      positiveProfit:    Positive profit
      shortLongPeriods:  Short better than long
      shortPeriod:       Short period (weeks)
      longPeriod:        Long period (weeks)
      longPercentage:    Long percentage
      winningPercentage: Winning % > value
      winningPercValue:  Value (%)
      equityAverage:     Equity over its average
      equityDays:        Average length (days)

      summary: Summary
      analysis: Analysis
      chart:
        unfProfit:   Unfiltered profit
        filProfit:   Filtered profit
        unfDrawdown: Unfiltered DD
        filDrawdown: Filtered DD
        average:     Average

# ==============================================================================
# ===
# === Errors
# ===
# ==============================================================================

errors:
  input:
    required: Value is required
    tooLong: Value is too long
