# ==============================================================================
# ===
# === Buttons
# ===
# ==============================================================================

button:
  create:   CREATE
  view:     VIEW
  edit:     EDIT
  delete:   DELETE
  filter:   FILTER
  save:     SAVE
  run:      RUN
  optimize: OPTIMIZE
  reload:   RELOAD
  cancel:   CANCEL
  abort:    ABORT
  close:    CLOSE
  use:      USE
  restart:  RESTART
  upload:   UPLOAD
  chart:    CHART
  ok:       Ok
  select:   SELECT
  presets:  PRESETS
  analyze:  ANALYZE
  replace:  REPLACE
  backtest: BACKTEST
  data:     DATA

# ==============================================================================
# ===
# === Left menu
# ===
# ==============================================================================

menu:
  main:
    _label: Main
    home: Home
  inventory:
    _label: Inventory
    dataProduct  : Data products
    brokerProduct: Broker products
    tradingSystem: Trading systems
  portfolio:
    _label: Portfolio
    tradingSystem: Trading systems
    monitoring   : Monitoring
  tool:
    _label: Tool
    biasAnalyses: Bias analyses

  admin:
    _label: Administration
    connections  : Connections
    config       : Configuration
    link         : GitHub

# ==============================================================================
# ===
# === Generic components
# ===
# ==============================================================================

flexTable:
  noData: Empty

simpleTable:
  noData: Empty

fileUpload:
  instructions: Drag and drop the file(s) here or click on "Browse Files".
  tipRemove: Remove file
  browseFiles: Browse Files

# ==============================================================================
# ===
# === Model
# ===
# ==============================================================================

model:
  tradingSystem:
    id              : Id
    createdAt       : Created at
    updatedAt       : Updated at
    name            : Name
    portfolioName   : Portfolio
    dataSymbol      : Data symbol
    brokerSymbol    : Broker symbol
    tradingSession  : Session

    code            : Code
    firstUpdate     : First update
    lastUpdate      : Last update
    closedProfit    : Closed profit
    tradingDays     : Trading days
    numTrades       : Num. of trades
    filterType      : Filter type
    filter          : Filter
    status          : Status

  connection:
    id                   : Id
    username             : Username
    code                 : Code
    name                 : Name
    systemCode           : System code
    systemName           : System name
    connectionCode       : Connected
    supportsData         : Data
    supportsBroker       : Broker
    supportsMultipleData : MData
    supportsInventory    : Inventory
    createdAt            : Created at
    updatedAt            : Updated at

  filterOptimiz:
    filterType:  Filter
    days:        (Old) Days
    newDays:     New days
    percentage:  Percentage
    netProfit:   Net profit
    avgTrade:    Average trade
    maxDrawdown: Max Drawdown

  dataProduct:
    id             : Id
    username       : Username
    symbol         : Symbol
    name           : Name
    marketType     : Market type
    productType    : Product type
    createdAt      : Created at
    updatedAt      : Updated at
    connectionCode : Connection
    systemCode     : System
    exchangeCode   : Exchange

  dataInstrument:
    id: Id
    symbol         : Symbol
    name           : Name
    expirationDate : Expiration date
    isContinuous   : Continuous
    dataFrom       : Data from
    dataTo         : Data to
    status         : Status
    productSymbol  : Product symbol
    connectionCode : Connection
    systemCode     : System

  dataPoint:
    time  : Date/time
    open  : Open
    high  : High
    low   : Low
    close : Close
    volume: Volume

  brokerProduct:
    id             : Id
    username       : Username
    symbol         : Symbol
    name           : Name
    pointValue     : Point value
    costPerTrade   : Cost per trade
    marginValue    : Margin value
    increment      : Increment
    marketType     : Market type
    productType    : Product type
    createdAt      : Created at
    updatedAt      : Updated at
    connectionCode : Connection
    currencyCode   : Currency
    exchangeCode   : Exchange

  presetProduct:
    symbol      : Symbol
    name        : Name
    increment   : Increment
    market      : Market
    product     : Product
    exchange    : Exchange
    pointValue  : Point value
    costPerTrade: Cost per trade
    margin      : Margin
    microFuture : Micro

  biasAnalysis:
    username       : Username
    name           : Name
    notes          : Notes
    dataSymbol     : Data symbol
    dataName       : Data name
    brokerSymbol   : Broken symbol
    brokerName     : Broker name
    brokerProductId: Broker product

  biasConfig:
    startDay   : Start day
    startSlot  : Start slot
    endDay     : End day
    endSlot    : End slot
    months     : Months
    excludes   : Excludes
    operation  : Operation
    grossProfit: Gross profit (estimate)
    netProfit  : Net profit (estimate)

  exchange:
    code : Code

  biasTrade:
    entryTime  : Entry time
    entryValue : Entry value
    exitTime   : Exit time
    exitValue  : Exit value
    operation  : Operation
    grossProfit: Gross profit
    netProfit  : Net profit

# ==============================================================================
# ===
# === Pages
# ===
# ==============================================================================

page:
  header:
    title: BitFever platform
  unknown:
    message: Unknown page

  # ==============================================================================

  inventory:
    tradingSystem:
      new:           New trading system
      name:          Name
      workspaceCode: Workspace
      portfolio:     Portfolio
      data:          Data symbol
      broker:        Broker symbol
      session:       Trading session

    dataProduct:
      new:   New data product
      edit:  Edit data product
      instruments: Instruments
      upload:
        title   : Data instrument upload
        success : Datafile successfully uploaded
        error   : Cannot upload datafile
        fileTimezone: File timezone
        parser  : Parser
        continuous: Continuous contract
      chart:
        fromDate : From date
        toDate   : To date
        timeframe: Timeframe
        timezone : Timezone
        exchange : Exchange
      data:
        fromDate : From date
        toDate   : To date
        timeframe: Timeframe
        timezone : Timezone
        exchange : Exchange
        tooManyDataPoints : Too many datapoints. Try reducing the time period or increasing the timeframe. Max 10.000 datapoints can be returned.

    brokerProduct:
      new:          New broker product
      edit:         Edit broker product
      connection:   Connection
      symbol:       Symbol
      name:         Name
      pointValue:   Point value
      costPerTrade: Cost per trade
      marginValue:  Margin value
      marketType:   Market
      productType:  Product
      exchange:     Exchange

  # ==============================================================================

  portfolio:
    tradingSystem:
      status:
        en: Enabled
        di: Disabled

    # ----------------------------------------------------------------------------

    monitoring:
      portfolios: Portfolios
      tradingSystems: Trading systems
      options: Options
      period: Period
      periods:
        - id: 30
          name: Last month
        - id: 60
          name: Last 2 months
        - id: 90
          name: Last 3 months
        - id: 180
          name: Last 6 months
        - id: 365
          name: Last year
        - id: 730
          name: Last 2 years
      chartType: Chart type
      chartTypes:
        - id: equities
          name: Equities
        - id: trades
          name: Trades
      showTotals:   Totals
      showRawProfit:   Raw profits
      showNetProfit:   Net profits
      showRawDrawdown: Raw drawdowns
      showNetDrawdown: Net drawdowns

      totalRawProfit:   Total raw profit
      totalNetProfit:   Total net profit
      totalRawDrawdown: Total raw drawdown
      totalNetDrawdown: Total net drawdown
      totalTrades:      Total trades

    # ----------------------------------------------------------------------------

    filtering:
      days:              Trading days
      positiveProfit:    Positive profit
      oldVsNew:          Old period vs new period
      oldDays:           Old period (trading days)
      newDays:           New period (trading days)
      oldPercentage:     Old period %
      winningPercentage: Winning % > value
      winningPercValue:  Value (%)
      equityAverage:     Equity over its average
      equityDays:        Average length (trading days)
      filterSaved:       Filter saved
      summary: Summary
      analysis: Analysis
      summ:
        name:
        unfiltered:   Unfiltered
        filtered:     Filtered
        netProfit:    Net profit
        maxDrawdown:  Max drawdown
        winningPerc:  Winning percentage
        averageTrade: Average trade

      chart:
        unfEquity:   Unfiltered equity
        filEquity:   Filtered equity
        unfDrawdown: Unfiltered DD
        filDrawdown: Filtered DD
        average:     Average
        equOverAvg:  Equity over average
        positProfit: Positive profit
        oldVsNew:    Old vs new period
        winningPerc: Winning % > value
        filterActivation: Filter activation

      optimize:
        title_params:   Filter optimization - Parameters
        title_progress: Filter optimization - Progress
        title_result:   Filter optimization - Result
        optimizeFor: Optimize for
        positiveProfit:  Positive profit
        oldVsNewPeriod:  Old vs new
        winningPerc:     Winning %
        equityVsAverage: Equity vs average
        selected:  Selected
        filter:    Filter
        parameter: Parameter
        options:   Options
        days:      Days
        oldDays:   Old days
        newDays:   New days
        oldPerc:   Old %
        percentage: Win %
        curValue : Current value
        minValue : Min value
        maxValue : Max value
        step     : Step
        fieldOptions:
          - id: net-profit
            name: Net profit
          - id: drawdrown
            name: Drawdown
          - id: avg-trade
            name: Average trade
        taCurrStep:   Current step
        taTotalSteps: Total steps
        taPercentage: Percentage
        taBestValue:  Best value
        taBaseValue:  Base value
        taOptimFor:   Optimize for
        taPosProfit:  Positive profit
        taOldVsNew:   Old vs new periods
        taWinPerc:    Winning percentage
        taEquVsAvg:   Equity vs average
        taDuration:   Duration
        taGain:       Gain
  instrumentSelector:
    message: Data instrument
    title  : Data instrument selector
  presetProductSelector:
    title  : Products selector

  # ==============================================================================

  tool:
    biasAnalysis:
      new:   New bias analysis
      edit:  Edit bias analysis
      selection   : Selection
      delta       : Delta
      labels      : Labels
      profit      : Profit
      pointValue  : Point value
      exclPeriods : Excluded periods
      periodFormat: Format is YEAR or YEAR-MONTH (like 2020-3)
      startPeriod : Start period
      endPeriod   : End period
      tabDetails  : Details
      tabStrategy : Strategy
      tabBacktest : Backtest
      gross       : Gross
      net         : Net
      avgTrade    : Avg trade

      backtestDialog:
        title           : Backtest results
        general         : General
        biasAnalysis    : Bias analysis
        brokerProduct   : Broker product
        backtestConfigs : Backtested configs
        biasConfig      : Bias config
        summary         : Backtest summary
        listOfTrades    : List of trades
        annualSummary   : Annual summary
        profitDistrib   : Profit distribution
        triggerSequences: Triggering sequences
        symbol          : Symbol
        name            : Name
        costPerTrade    : Cost per trade
        pointValue      : Point value (multiplier)
        startPeriod     : Start period
        endPeriod       : End period
        months          : Selected months
        excludes        : Excluded periods
        operation       : Operation
        gross           : Gross
        net             : Net
        profit          : Profit
        avgTrade        : Average trade
        estGrossProfit  : Gross profit (estimated)
        estNetProfit    : Net profit (estimated)
        profits         : Profits
        tradeCount      : Trades count

  # ==============================================================================

  admin:
    config:
      title: Configuration

    # ----------------------------------------------------------------------------

    connection:
      new: New connection
      code: Code
      name: Name
      system: System

  # ==============================================================================

# ==============================================================================

# ==============================================================================
# ===
# === Maps
# ===
# ==============================================================================

map:
  market:
    IN: Index
    EN: Energy
    ME: Metal
    GR: Grain
    BO: Bond
    MT: Meat
    SO: Soft
    FX: Currency

  product:
    FU: Futures

  fileTimezone:
    utc: GMT/UTC
    exc: Exchange

  timeframe:
    1m : 1 min
    5m : 5 min
    10m: 10 min
    15m: 15 min
    30m: 30 min
    60m: 1 hour

  dows:
    sun: Sunday
    mon: Monday
    tue: Tuesday
    wed: Wednesday
    thu: Thursday
    fri: Friday
    sat: Saturday

  months:
    jan: January
    feb: February
    mar: March
    apr: April
    may: May
    jun: June
    jul: July
    aug: August
    sep: September
    oct: October
    nov: November
    dec: December

  operation:
    long : Long
    short: Short

# ==============================================================================

list:
  dowShort: [ Sun, Mon, Tue, Wed, Thu, Fri, Sat ]
  dowLong : [ Sunday, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday ]
  monShort: [ Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec ]

# ==============================================================================
# ===
# === Errors
# ===
# ==============================================================================

errors:
  input:
    required: Value is required
    tooLong: Value is too long
    minValue: Min value is
    maxValue: Max value is
