# ==============================================================================
# ===
# === Buttons
# ===
# ==============================================================================

button:
  create:   CREATE
  view:     VIEW
  edit:     EDIT
  filter:   FILTER
  save:     SAVE
  run:      RUN
  optimize: OPTIMIZE
  reload:   RELOAD
  cancel:   CANCEL
  abort:    ABORT
  close:    CLOSE
  use:      USE
  restart:  RESTART
  upload:   UPLOAD
  chart:    CHART
  ok:       Ok

# ==============================================================================
# ===
# === Left menu
# ===
# ==============================================================================

menu:
  main:
    _label: Main
    home: Home
  inventory:
    _label: Inventory
    productData  : Product (data)
    productBroker: Product (broker)
    tradingSystem: Trading systems
  portfolio:
    _label: Portfolio
    tradingSystem: Trading systems
    monitoring   : Monitoring
  admin:
    _label: Administration
    connections  : Connections
    config       : Configuration
    link         : GitHub

# ==============================================================================
# ===
# === Flex table
# ===
# ==============================================================================

flexTable:
  noData: No data

simpleTable:
  noData: No data

fileUpload:
  instructions: Drag and drop the file(s) here or click on "Browse Files".
  tipRemove: Remove file
  browseFiles: Browse Files

# ==============================================================================
# ===
# === Model
# ===
# ==============================================================================

model:
  tradingSystem:
    id              : Id
    createdAt       : Created at
    updatedAt       : Updated at
    name            : Name
    portfolioName   : Portfolio
    dataSymbol      : Data symbol
    brokerSymbol    : Broker symbol
    tradingSession  : Session

    code            : Code
    firstUpdate     : First update
    lastUpdate      : Last update
    closedProfit    : Closed profit
    tradingDays     : Trading days
    numTrades       : Num. of trades
    filterType      : Filter type
    filter          : Filter
    status          : Status

#  instrument:
#    id             : Id
#    ticker         : Ticker;
#    name           : Name;
#    createdAt      : Created at
#    updatedAt      : Updated at

  connection:
    id                   : Id
    username             : Username
    code                 : Code
    name                 : Name
    systemCode           : System code
    systemName           : System name
    connectionCode       : Connected
    supportsData         : Data
    supportsBroker       : Broker
    supportsMultipleData : MData
    supportsInventory    : Inventory
    createdAt            : Created at
    updatedAt            : Updated at

  filterOptimiz:
    filterType:  Filter
    days:        (Old) Days
    newDays:     New days
    percentage:  Percentage
    netProfit:   Net profit
    avgTrade:    Average trade
    maxDrawdown: Max Drawdown

  productData:
    id             : Id
    username       : Username
    symbol         : Symbol
    name           : Name
    increment      : Increment
    marketType     : Market type
    productType    : Product type
    createdAt      : Created at
    updatedAt      : Updated at
    connectionCode : Connection
    systemCode     : System
    exchangeCode   : Exchange
    localClass     : Local class

  instrumentData:
    id: Id
    symbol         : Symbol
    name           : Name
    expirationDate : Expiration date
    isContinuous   : Continuous

  productBroker:
    id             : Id
    username       : Username
    symbol         : Symbol
    name           : Name
    pointValue     : Point value
    costPerTrade   : Cost per trade
    marginValue    : Margin value
    marketType     : Market type
    productType    : Product type
    createdAt      : Created at
    updatedAt      : Updated at
    connectionCode : Connection
    currencyCode   : Currency
    exchangeCode   : Exchange

# ==============================================================================
# ===
# === Pages
# ===
# ==============================================================================

page:
  header:
    title: BitFever platform
  unknown:
    message: Unknown page

  # ==============================================================================

  inventory:
    tradingSystem:
      new:           New trading system
      name:          Name
      workspaceCode: Workspace
      portfolio:     Portfolio
      data:          Data symbol
      broker:        Broker symbol
      session:       Trading session

    productData:
      new:   New product for data
      edit:  Edit product for data
      instruments: Instruments
      upload:
        title  : Instrument data upload
        success: Datafile successfully uploaded
        error  : Cannot upload datafile

    productBroker:
      new:          New product for broker
      edit:         Edit product for broker
      connection:   Connection
      symbol:       Symbol
      name:         Name
      pointValue:   Point value
      costPerTrade: Cost per trade
      marginValue:  Margin value
      marketType:   Market
      productType:  Product
      localClass:   Local class
      exchange:     Exchange

  # ==============================================================================

  admin:
    config:
      title: Configuration

    # ----------------------------------------------------------------------------

    connection:
      new: New connection
      code: Code
      name: Name
      system: System

  # ==============================================================================

  portfolio:
    tradingSystem:
      status:
        en: Enabled
        di: Disabled

    # ----------------------------------------------------------------------------

    monitoring:
      portfolios: Portfolios
      tradingSystems: Trading systems
      options: Options
      period: Period
      periods:
        - id: 30
          name: Last month
        - id: 60
          name: Last 2 months
        - id: 90
          name: Last 3 months
        - id: 180
          name: Last 6 months
        - id: 365
          name: Last year
        - id: 730
          name: Last 2 years
      chartType: Chart type
      chartTypes:
        - id: equities
          name: Equities
        - id: trades
          name: Trades
      showTotals:   Totals
      showRawProfit:   Raw profits
      showNetProfit:   Net profits
      showRawDrawdown: Raw drawdowns
      showNetDrawdown: Net drawdowns

      totalRawProfit:   Total raw profit
      totalNetProfit:   Total net profit
      totalRawDrawdown: Total raw drawdown
      totalNetDrawdown: Total net drawdown
      totalTrades:      Total trades

    # ----------------------------------------------------------------------------

    filtering:
      days:              Trading days
      positiveProfit:    Positive profit
      oldVsNew:          Old period vs new period
      oldDays:           Old period (trading days)
      newDays:           New period (trading days)
      oldPercentage:     Old period %
      winningPercentage: Winning % > value
      winningPercValue:  Value (%)
      equityAverage:     Equity over its average
      equityDays:        Average length (trading days)
      filterSaved:       Filter saved
      summary: Summary
      analysis: Analysis
      summ:
        name:
        unfiltered:   Unfiltered
        filtered:     Filtered
        netProfit:    Net profit
        maxDrawdown:  Max drawdown
        winningPerc:  Winning percentage
        averageTrade: Average trade

      chart:
        unfEquity:   Unfiltered equity
        filEquity:   Filtered equity
        unfDrawdown: Unfiltered DD
        filDrawdown: Filtered DD
        average:     Average
        equOverAvg:  Equity over average
        positProfit: Positive profit
        oldVsNew:    Old vs new period
        winningPerc: Winning % > value
        filterActivation: Filter activation

      optimize:
        title_params:   Filter optimization - Parameters
        title_progress: Filter optimization - Progress
        title_result:   Filter optimization - Result
        optimizeFor: Optimize for
        positiveProfit:  Positive profit
        oldVsNewPeriod:  Old vs new
        winningPerc:     Winning %
        equityVsAverage: Equity vs average
        selected:  Selected
        filter:    Filter
        parameter: Parameter
        options:   Options
        days:      Days
        oldDays:   Old days
        newDays:   New days
        oldPerc:   Old %
        percentage: Win %
        curValue : Current value
        minValue : Min value
        maxValue : Max value
        step     : Step
        fieldOptions:
          - id: net-profit
            name: Net profit
          - id: drawdrown
            name: Drawdown
          - id: avg-trade
            name: Average trade
        taCurrStep:   Current step
        taTotalSteps: Total steps
        taPercentage: Percentage
        taBestValue:  Best value
        taBaseValue:  Base value
        taOptimFor:   Optimize for
        taPosProfit:  Positive profit
        taOldVsNew:   Old vs new periods
        taWinPerc:    Winning percentage
        taEquVsAvg:   Equity vs average
        taDuration:   Duration
        taGain:       Gain

# ==============================================================================
# ===
# === Maps
# ===
# ==============================================================================

map:
  market:
    IN: Index
    EN: Energy
    ME: Metal
    GR: Grain
    BO: Bond
    MT: Meat
    SO: Soft
    FX: Currency

  product:
    FU: Futures

# ==============================================================================
# ===
# === Errors
# ===
# ==============================================================================

errors:
  input:
    required: Value is required
    tooLong: Value is too long
    minValue: Min value is
    maxValue: Max value is
