#--- Indices --------------------------------

- symbol:
    default       : ESc
  name            : E-Mini S&P 500
  increment       : 0.25
  market          : IN
  product         : FU
  exchange        : CME
  pointValue      : 50
  costPerOperation: 30
  margin          : 0
  strategies      : reversal(good), trendf(hard), bias(no)
  months          : HMUZ
  rollover        : sd6

- symbol:
    default       : MES
  name            : Micro E-Mini S&P 500
  increment       : 0.25
  market          : IN
  product         : FU
  exchange        : CME
  pointValue      : 5
  costPerOperation: 4
  margin          : 1314
  strategies      : reversal(good), trendf(hard), bias(no)
  months          : HMUZ
  micro           : true
  rollover        : sd6

- symbol:
    default       : NQ
  name            : E-Mini Nasdaq-100
  increment       : 0.25
  market          : IN
  product         : FU
  exchange        : CME
  pointValue      : 20
  costPerOperation: 40
  margin          : 36070
  months          : HMUZ
  rollover        : sd6

- symbol:
    default       : MNQ
  name            : Micro E-mini Nasdaq 100
  increment       : 0.25
  market          : IN
  product         : FU
  exchange        : CME
  pointValue      : 2
  costPerOperation: 5
  margin          : 3607
  months          : HMUZ
  micro           : true
  rollover        : sd6

- symbol:
    default       : YM
  name            : Mini Dow Jones 30
  increment       : 1
  market          : IN
  product         : FU
  exchange        : CME
  pointValue      : 5
  costPerOperation: 0
  margin          : 12800
  months          : HMUZ
  rollover        : sd6

- symbol:
    default       : MYM
  name            : Micro Dow Jones 30
  increment       : 1
  market          : IN
  product         : FU
  exchange        : CME
  pointValue      : 0.5
  costPerOperation: 5
  margin          : 1280
  months          : HMUZ
  micro           : true
  rollover        : sd6

- symbol:
    default       : FDAX
  name            : DAX
  increment       : 1
  market          : IN
  product         : FU
  exchange        : EUREX
  pointValue      : 25
  costPerOperation: 0
  margin          : 0
  strategies      : bias(good), reversal(good,first-half-day), trendf(intraday)
  months          : HMUZ
  rollover        :

- symbol:
    default       : FDXM
  name            : Mini DAX
  increment       : 1
  market          : IN
  product         : FU
  exchange        : EUREX
  pointValue      : 5
  costPerOperation: 0
  margin          : 0
  strategies      : bias, reversal(first-half-day), intraday
  months          : HMUZ
  rollover        :

- symbol:
    default       : FDXS
  name            : Micro DAX
  increment       : 1
  market          : IN
  product         : FU
  exchange        : EUREX
  pointValue      : 1
  costPerOperation: 6
  margin          : 1600
  strategies      : bias, reversal(first-half-day), intraday
  months          : HMUZ
  micro           : true
  rollover        :

- symbol:
    default       : FESX
  name            : Euro Stoxx 50
  increment       : 0
  market          : IN
  product         : FU
  exchange        : EUREX
  pointValue      : 0
  costPerOperation: 0
  margin          : 0
  months          : HMUZ
  rollover        :

#--- Metals --------------------------------

- symbol:
    default       : GC
  name            : Gold
  increment       : 0.1
  market          : ME
  product         : FU
  exchange        : COMEX
  pointValue      : 100
  costPerOperation: 20
  margin          : 16034c
  strategies      : bias
  months          : GJMQvZ
  rollover        : sd30

- symbol:
    default       : MGC
  name            : Micro Gold
  increment       : 0.1
  market          : ME
  product         : FU
  exchange        : COMEX
  pointValue      : 10
  costPerOperation: 4
  margin          : 1604
  strategies      : bias
  micro           : true
  months          : GJMQvZ
  rollover        : sd30

- symbol:
    default       : PL
  name            : Platinum
  increment       : 0.1
  market          : ME
  product         : FU
  exchange        : NYMEX
  pointValue      : 50
  costPerOperation: 0
  margin          : 0
  months          : FJNV
  rollover        :

- symbol:
    default       : PLM
  name            : Micro Platinum
  increment       : 0.1
  market          : ME
  product         : FU
  exchange        : NYMEX
  pointValue      : 10
  costPerOperation: 0
  margin          : 0
  months          : FJNV
  micro           : true
  rollover        :

- symbol:
    default       : SI
  name            : Silver
  increment       : 0.005
  market          : ME
  product         : FU
  exchange        : COMEX
  pointValue      : 5000
  costPerOperation: 0
  margin          : 0
  months          : HKNUZ
  rollover        :

- symbol:
    default       : HG
  name            : Copper
  increment       : 0.0005
  market          : ME
  product         : FU
  exchange        : COMEX
  pointValue      : 25000
  costPerOperation: 0
  margin          : 0
  months          : HKNUZ
  rollover        :

- symbol:
    default       : MHG
  name            : Micro Copper
  increment       : 0.0005
  market          : ME
  product         : FU
  exchange        : COMEX
  pointValue      : 2500
  costPerOperation: 0
  margin          : 0
  micro           : true
  months          : HKNUZ
  rollover        :

#--- Energy --------------------------------

- symbol:
    default       : CL
  name            : Crude Oil
  increment       : 0.01
  market          : EN
  product         : FU
  exchange        : NYMEX
  pointValue      : 1000
  costPerOperation: 30
  margin          : 0
  strategies      : bias(good), reversal(no), trendf(intraday, overnight), 5min
  months          : FGHJKMNQUVXZ
  rollover        : sd6

- symbol:
    default       : MCL
  name            : Micro Crude Oil
  increment       : 0.01
  market          : EN
  product         : FU
  exchange        : NYMEX
  pointValue      : 100
  costPerOperation: 4
  margin          : 2700
  strategies      : bias(good), reversal(no), trendf(intraday, overnight), 5min
  months          : FGHJKMNQUVXZ
  micro           : true
  rollover        : sd6

- symbol:
    default       : HO
  name            : NY Harbor USLD (Heating Oil)
  increment       : 0.0001
  market          : EN
  product         : FU
  exchange        : NYMEX
  pointValue      : 42000
  costPerOperation: 0
  margin          : 0
  months          : FGHJKMNQUVXZ
  rollover        :

- symbol:
    default       : MHO
  name            : Micro NY Harbor USLD (Heating Oil)
  increment       : 0.0001
  market          : EN
  product         : FU
  exchange        : NYMEX
  pointValue      : 4200
  costPerOperation: 0
  margin          : 0
  months          : FGHJKMNQUVXZ
  micro           : true
  rollover        :

- symbol:
    default       : NG
  name            : Henry Hub Natural Gas
  increment       : 0.001
  market          : EN
  product         : FU
  exchange        : NYMEX
  pointValue      : 10000
  costPerOperation: 0
  margin          : 0
  months          : FGHJKMNQUVXZ
  rollover        :

- symbol:
    default       : MNG
  name            : Micro Henry Hub Natural Gas
  increment       : 0.001
  market          : EN
  product         : FU
  exchange        : NYMEX
  pointValue      : 1000
  costPerOperation: 0
  margin          : 0
  months          : FGHJKMNQUVXZ
  micro           : true
  rollover        :

- symbol:
    default       : RB
  name            : RBOB Gasoline
  increment       : 0.0001
  market          : EN
  product         : FU
  exchange        : NYMEX
  pointValue      : 42000
  costPerOperation: 0
  margin          : 0
  months          : FGHJKMNQUVXZ
  rollover        :

- symbol:
    default       : MRB
  name            : Micro RBOB Gasoline
  increment       : 0.0001
  market          : EN
  product         : FU
  exchange        : NYMEX
  pointValue      : 4200
  costPerOperation: 0
  margin          : 0
  months          : FGHJKMNQUVXZ
  micro           : true
  rollover        :

#--- Currencies --------------------------------

- symbol:
    default       : 6A
    TS            : AD
  name            : Australian Dollar
  increment       : 0.00005
  market          : FX
  product         : FU
  exchange        : CME
  pointValue      : 100000
  costPerOperation: 0
  margin          : 0
  months          : HMUZ

- symbol:
    default       : 6B
    TS            : BP
  name            : British Pound
  increment       : 0.0001
  market          : FX
  product         : FU
  exchange        : CME
  pointValue      : 62500
  costPerOperation: 0
  margin          : 2977
  months          : HMUZ
  rollover        : sd4

- symbol:
    default       : M6B
  name            : Micro British Pound
  increment       : 0.0001
  market          : FX
  product         : FU
  exchange        : CME
  pointValue      : 6250
  costPerOperation: 2
  margin          : 313
  months          : HMUZ
  micro           : true
  rollover        : sd4

- symbol:
    default       : 6C
    TS            : CD
  name            : Canadian Dollar
  increment       : 0.00005
  market          : FX
  product         : FU
  exchange        : CME
  pointValue      : 100000
  costPerOperation: 0
  margin          : 0
  months          : HMUZ
  rollover        :

- symbol:
    default       : 6E
    TS            : EC
  name            : Euro FX
  increment       : 0.00005
  market          : FX
  product         : FU
  exchange        : CME
  pointValue      : 125000
  costPerOperation: 8
  margin          : 3685
  strategies      : bias, 5min
  months          : HMUZ
  rollover        :

- symbol:
    default       : E7
  name            : E-Mini Euro FX
  increment       : 0.0001
  market          : FX
  product         : FU
  exchange        : CME
  pointValue      : 62500
  costPerOperation: 8
  margin          : 1842
  strategies      : bias, reversal 1h, 5min
  months          : HMUZ
  rollover        :

- symbol:
    default       : 6J
    TS            : JY
  name            : Japanese Yen
  increment       : 0.0000001
  market          : FX
  product         : FU
  exchange        : CME
  pointValue      : 12500000
  costPerOperation: 0
  margin          : 0
  months          : HMUZ
  rollover        :

- symbol:
    default       : 6N
    TS            : NE1
  name            : New Zealand Dollar
  increment       : 0
  market          : FX
  product         : FU
  exchange        : CME
  pointValue      : 0
  costPerOperation: 0
  margin          : 0
  months          : HMUZ
  rollover        :

#--- Grains --------------------------------

- symbol:
    default       : ZS
    TS            : S
  name            : Soybean
  increment       :
  market          : GR
  product         : FU
  exchange        : CBOT
  pointValue      :
  costPerOperation: 50
  margin          : 0
  months          : FHKNquX
  rollover        :

- symbol:
    default       : ZC
    TS            : C
  name            : Corn
  increment       :
  market          : GR
  product         : FU
  exchange        : CBOT
  pointValue      :
  costPerOperation: 0
  margin          : 0
  months          : HKNUZ
  rollover        :

- symbol:
    default       : ZW
    TS            : W
  name            : Chicago SRW Wheat
  increment       : 0.0025
  market          : GR
  product         : FU
  exchange        : CBOT
  pointValue      : 5000
  costPerOperation: 0
  margin          : 2800
  notes           : Verify pointValue & increment
  months          : HKNUZ
  rollover        :

#--- Softs --------------------------------

- symbol:
    default       : KC
  name            : Coffee "C"
  increment       : 0.05
  market          : SO
  product         : FU
  exchange        : IFUS
  pointValue      : 375
  costPerOperation: 0
  margin          : 0
  months          : HKNUZ
  rollover        :

- symbol:
    default       : CT
  name            : Cotton N. 2
  increment       : 0.01
  market          : SO
  product         : FU
  exchange        : IFUS
  pointValue      : 500
  costPerOperation: 0
  margin          : 0
  months          : HKNvZ
  rollover        :

#--- Bonds --------------------------------

- symbol:
    default       : ZN
    TS            : TY
  name            : 10 Yr U.S. T-Note
  increment       : 0.015625
  market          : BO
  product         : FU
  exchange        : CBOT
  pointValue      : 1000
  costPerOperation: 0
  margin          : 0
  months          : HMUZ
  rollover        :

- symbol:
    default       : ZB
    TS            : US
  name            : U.S. Treasury Bond (30y)
  increment       : 0.03125
  market          : BO
  product         : FU
  exchange        : CBOT
  pointValue      : 1000
  costPerOperation: 0
  margin          : 0
  months          : HMUZ
  rollover        :

- symbol:
    default       : FGBL
  name            : Bund
  increment       : 0
  market          : BO
  product         : FU
  exchange        : EUREX
  pointValue      : 0
  costPerOperation: 0
  margin          : 0
  months          : HMUZ
  rollover        :

#--- Meats --------------------------------

- symbol:
    default       : GF
    TS            : FC
  name            : Feeder Cattle
  increment       :
  market          : MT
  product         : FU
  exchange        : CME
  pointValue      :
  costPerOperation: 0
  margin          : 0
  months          : FHJKQUVX
  rollover        :

- symbol:
    default       : HE
    TS            : LH
  name            : Lean Hog
  increment       :
  market          : MT
  product         : FU
  exchange        : CME
  pointValue      :
  costPerOperation: 0
  margin          : 0
  strategies      : overnight
  months          : GJMQVZ
  rollover        :

- symbol:
    default       : LE
    TS            : LC
  name            : Live Cattle
  increment       :
  market          : MT
  product         : FU
  exchange        : CME
  pointValue      :
  costPerOperation: 0
  margin          : 0
  strategies      : reversal(good), trendf(overnight, weak), bias(no)
  months          : GJMQVZ
  rollover        :

# cocoa: overnight
